repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: file-contents-sorter
        files: ".gitignore$"
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=120, --extend-ignore=F401 __init__.py]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
    -   id: commitizen
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args: [--config=setup.cfg]
        pass_filenames: false
        always_run: true
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        entry.: isort .
        language: python
        pass_filenames: false
        always_run: true
